USE Wisdom_RubberProject_Practice_3;

-- Drop tables one by one
DROP TABLE IF EXISTS ChargingStatus;
DROP TABLE IF EXISTS DroneImage;
DROP TABLE IF EXISTS DroneInformation;
DROP TABLE IF EXISTS Drone;
DROP TABLE IF EXISTS Environment;
DROP TABLE IF EXISTS Blade;
DROP TABLE IF EXISTS RobotTapping;
DROP TABLE IF EXISTS Energy;
DROP TABLE IF EXISTS Robot;
DROP TABLE IF EXISTS SensorControlSystem;
DROP TABLE IF EXISTS Task;
DROP TABLE IF EXISTS PlanDetail;
DROP TABLE IF EXISTS [Plan];
DROP TABLE IF EXISTS RubberTreeInformation;
DROP TABLE IF EXISTS RubberTree;
DROP TABLE IF EXISTS Field;
DROP TABLE IF EXISTS UserInfo;
DROP TABLE IF EXISTS Account;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS Country;
DROP TABLE IF EXISTS Lidar;
DROP TABLE IF EXISTS Camera;
DROP TABLE IF EXISTS Radar;
DROP TABLE IF EXISTS ChargingStation;
